{% set name = "pytube" %}
{% set version = "12.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytube-{{ version }}.tar.gz
  sha256: 2d34a484f81cae106ea84e8c00871f97dcc293e8ed8c074e65abc4119f02c98f

build:
  number: 0
  noarch: python
  entry_points:
    - pytube = pytube.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - pytube
    - pytube.contrib
  commands:
    - pip check
    - pytube --help
  requires:
    - pip

about:
  home: https://pytube.io/
  license: Unlicense
  license_family: Other
  license_file: LICENSE
  summary: A lightweight, dependency-free Python library (and command-line utility) for downloading YouTube Videos.
  description: |
    pytube is a very serious, lightweight, dependency-free Python library
    (and command-line utility) for downloading YouTube Videos.
  doc_url: https://pytube.io
  dev_url: https://github.com/pytube/pytube

extra:
  recipe-maintainers:
    - jan-janssen
